dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T simple_math-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usimbion0:$BINTRAY_API_KEY "https://api.bintray.com/content/simbion0/deb_pack/test/$TRAVIS_BUILD_NUMBER/simple_math-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
