os: linux
dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - libboost-test-dev
install:
  - pip install --user conan
  - conan user
script:
  - conan install .
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
before_deploy:
  - sed -i "s/__VERSION__/$TRAVIS_BUILD_NUMBER/g" bintray_settings.json
  - cat bintray_settings.json
deploy:
  skip_cleanup: true
  provider: bintray
  file: bintray_settings.json
  user: $BINTRAY_USER
  key:  $BINTRAY_API_KEY